/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'alex' at '10/11/16 12:49 PM' with Gradle 2.14
 *
 * @author alex, @date 10/11/16 12:49 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
